#ifndef FFTA_REACTION_IDS_H
#define FFTA_REACTION_IDS_H
/* Central hidden-only rows; these do not enter AP/command/AI lesson lists. */
#define FFTA_GLOBAL_ACTION_COUNT 438u
#define FFTA_COUNTER_DRAW_ACTION 435u
#define FFTA_ABSORB_ACTION 436u
#define FFTA_GIL_SNAPPER_ACTION 437u
#define FFTA_COUNTER_DRAW_KIND 132u
#define FFTA_ABSORB_KIND 138u
#define FFTA_GIL_SNAPPER_KIND 139u
#define FFTA_COUNTER_DRAW_READY (1u<<29)
#define FFTA_COUNTER_DRAW_CLAIM 256u
#define FFTA_ABSORB_QUEUED 8192u
#define FFTA_GIL_SNAPPER_QUEUED 16384u
#define FFTA_COUNTER_DRAW_QUEUED 32768u
#endif
