"""Retention for generated build outputs. Deterministic; no model calls.

Generated probe trees grow by gigabytes per run and nothing removed them,
which filled the system volume (see notes/resource-incident-2026-09-15.md).
This pruner keeps every report, log and manifest, and removes only bulk
binary outputs that are regenerated by the builders or are historical
emulator captures:

* integrated-jobs: the current candidate (from current.json), every candidate
  named by a scripts/*.json test plan, and the newest --keep-candidates other
  candidates keep everything. Other candidates and other base ROM trees lose
  ROM images, emulator states, RAM dumps and screenshots.
* other probe families: sha-named directories not referenced by any manifest,
  report or plan lose only emulator captures (.state/.ram/.srm/.iwram/.png);
  ROM/ELF/BIN build inputs are never touched there because builders read
  fixtures from earlier probe directories.
* reproducibility: only the newest --keep-reproducibility runs keep their
  private workspace copy; reports and logs remain for every run.

Run with --dry-run to see what would be removed. The runner calls this after
each run; it can also be run standalone.
"""
import argparse
import datetime as dt
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from resource_guard import WorkspaceLock  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
PROBES = ROOT / 'build/expansion/probes'
INTEGRATED = PROBES / 'integrated-jobs'
REPRODUCIBILITY = ROOT / 'build/reproducibility'
LOCK = ROOT / 'build/expansion/test-runs/runner.lock'
SHA = re.compile(r'^[0-9a-f]{40}$')
SHA_ANYWHERE = re.compile(r'[0-9a-f]{40}')
BULK = {'.gba', '.state', '.ram', '.srm', '.iwram', '.png', '.a', '.o'}
CAPTURES = {'.state', '.ram', '.srm', '.iwram', '.png'}


def checked_path(path):
    """Fail closed before touching links or anything outside private build roots."""
    path = pathlib.Path(path).absolute()
    build = ROOT / 'build'
    if not path.is_relative_to(build):
        raise ValueError('Prune path outside build: ' + str(path))
    for part in (path, *path.parents):
        if part.is_symlink() or part.is_junction():
            raise ValueError('Prune path contains a link: ' + str(part))
        if part == ROOT:
            break
    resolved = path.resolve()
    if not any(resolved.is_relative_to(root.resolve()) and resolved != root.resolve()
               for root in (PROBES, REPRODUCIBILITY)):
        raise ValueError('Prune path outside approved output trees: ' + str(path))
    return path


def referenced_shas():
    """Every 40-hex identifier named by a manifest, report or plan."""
    found = set()
    sources = list(PROBES.rglob('current.json')) + list(PROBES.rglob('report.json')) \
        + list(PROBES.rglob('manifest.json')) + list((ROOT / 'scripts').glob('*.json')) \
        + list((ROOT / 'notes').glob('*.json'))
    for path in sources:
        # Manifests inside stale candidates reference only themselves and their
        # inputs; a manifest three levels below integrated-jobs is such a case.
        if path.is_relative_to(INTEGRATED) and len(path.relative_to(INTEGRATED).parts) > 2:
            continue
        try:
            found.update(SHA_ANYWHERE.findall(path.read_text(encoding='utf-8', errors='replace')))
        except OSError:
            continue
    return found


def integrated_keep(keep_candidates):
    """Return (base, candidate) directory pairs that keep everything."""
    keep = set()
    current = INTEGRATED / 'current.json'
    if current.is_file():
        rom = pathlib.Path(json.loads(current.read_text(encoding='utf-8'))['path'])
        keep.add((rom.parents[1].name, rom.parent.name))
    for plan in (ROOT / 'scripts').glob('*.json'):
        for base, candidate in re.findall(r'integrated-jobs[\\/]([0-9a-f]{40})[\\/]([0-9a-f]{40})',
                                          plan.read_text(encoding='utf-8', errors='replace')):
            keep.add((base, candidate))
    others = []
    for base in INTEGRATED.iterdir():
        if base.is_dir() and SHA.match(base.name):
            for candidate in base.iterdir():
                if candidate.is_dir() and SHA.match(candidate.name) and (base.name, candidate.name) not in keep:
                    others.append((candidate.stat().st_mtime, base.name, candidate.name))
    for _, base, candidate in sorted(others, reverse=True)[:keep_candidates]:
        keep.add((base, candidate))
    return keep


def remove_files(directory, suffixes, plan, dry_run, reason):
    checked_path(directory)
    for path in directory.rglob('*'):
        checked_path(path)
        if path.is_file() and path.suffix.lower() in suffixes:
            plan['bytes'] += path.stat().st_size
            plan['files'] += 1
            plan['reasons'][reason] = plan['reasons'].get(reason, 0) + 1
            if not dry_run:
                path.unlink()


def remove_tree(directory, plan, dry_run, reason):
    import shutil
    checked_path(directory)
    for path in directory.rglob('*'):
        checked_path(path)
        if path.is_file():
            plan['bytes'] += path.stat().st_size
            plan['files'] += 1
    plan['reasons'][reason] = plan['reasons'].get(reason, 0) + 1
    if not dry_run:
        shutil.rmtree(directory)


def prune(keep_candidates=1, keep_reproducibility=1, dry_run=False):
    if keep_candidates < 0 or keep_reproducibility < 0:
        raise ValueError('Retention counts must be nonnegative')
    plan = {'dryRun': dry_run, 'bytes': 0, 'files': 0, 'reasons': {}, 'kept': {}}
    if INTEGRATED.is_dir():
        keep = integrated_keep(keep_candidates)
        plan['kept']['integratedCandidates'] = sorted(f'{b}/{c}' for b, c in keep)
        keep_bases = {b for b, _ in keep}
        for base in INTEGRATED.iterdir():
            if not (base.is_dir() and SHA.match(base.name)):
                continue
            if base.name not in keep_bases:
                remove_files(base, BULK, plan, dry_run, 'integrated-jobs stale base')
                continue
            for entry in base.iterdir():
                if entry.is_dir() and SHA.match(entry.name) and (base.name, entry.name) not in keep:
                    remove_files(entry, BULK, plan, dry_run, 'integrated-jobs stale candidate')
    if PROBES.is_dir():
        referenced = referenced_shas()
        for family in PROBES.iterdir():
            if not family.is_dir() or family == INTEGRATED:
                continue
            for entry in family.iterdir():
                if entry.is_dir() and SHA.match(entry.name) and entry.name not in referenced:
                    remove_files(entry, CAPTURES, plan, dry_run, f'unreferenced captures in {family.name}')
    if REPRODUCIBILITY.is_dir():
        runs = sorted((p for p in REPRODUCIBILITY.iterdir() if p.is_dir()), key=lambda p: p.name)
        latest = REPRODUCIBILITY / 'latest.json'
        protected = set(runs[-keep_reproducibility:] if keep_reproducibility else [])
        if latest.is_file():
            protected.add(pathlib.Path(json.loads(latest.read_text(encoding='utf-8'))['report']).parent)
        plan['kept']['reproducibilityWorkspaces'] = sorted(p.name for p in protected)
        for run in runs:
            workspace = run / 'workspace'
            if run not in protected and workspace.is_dir():
                remove_tree(workspace, plan, dry_run, 'reproducibility workspace')
    plan['gigabytes'] = round(plan['bytes'] / 1024 ** 3, 2)
    return plan


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--dry-run', action='store_true')
    parser.add_argument('--keep-candidates', type=int, default=1,
                        help='Unreferenced integrated candidates kept intact, newest first')
    parser.add_argument('--keep-reproducibility', type=int, default=1,
                        help='Newest reproducibility runs whose workspace copy is kept')
    options = parser.parse_args()
    with WorkspaceLock(LOCK):
        plan = prune(options.keep_candidates, options.keep_reproducibility, options.dry_run)
    plan['finished'] = dt.datetime.now(dt.timezone.utc).isoformat()
    if not options.dry_run:
        report = ROOT / 'build/expansion/prune-latest.json'
        report.write_text(json.dumps(plan, indent=2) + '\n', encoding='utf-8')
    print(json.dumps(plan, indent=2))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
